name: Sync HKO Rainfall Data

on:
  schedule:
    - cron: '*/10 * * * *' # Tries to run every 10 minutes (Subject to GitHub queue delays)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Latest CSV from HKO
        run: |
          curl -sL "https://data.weather.gov.hk/weatherAPI/hko_data/F3/Gridded_rainfall_nowcast_tc.csv" -o Gridded_rainfall_nowcast_tc.csv

      - name: Commit and Push if updated
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Gridded_rainfall_nowcast_tc.csv
          if git diff --staged --quiet; then
            echo "No changes in rainfall data."
            exit 0
          else
            git commit -m "Automated Sync: Updated live HKO rainfall map data"
            git push
          fi
